config/routes.rb
EmailMe::Engine.routes.draw do
  resources :mail_templates, only: [:index, :edit, :update] do
    member do
      post 'preview'
    end
  end
  root 'mail_templates#index'
end

app/models/email_me/mail_template.rb
module EmailMe
  class MailTemplate < ActiveRecord::Base
    default_scope { order(:id) }
  end
end

app/controllers/email_me/application_controller.rb
module EmailMe
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/email_me/mail_templates_controller.rb
require_dependency "email_me/application_controller"

module EmailMe
  class MailTemplatesController < ApplicationController
    before_action :set_mail_template, only: [:show, :edit, :update, :destroy]

    # GET /mail_templates
    def index
      @mail_templates = MailTemplate.all
    end

    # GET /mail_templates/1/edit
    def edit
      @replacement_fields = EmailMe.replacement_fields
    end

    def preview
      # TODO figure out renderer options, and make as a class variable?
      content = preview_params[:content]
      @preview_html = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(content)
      respond_to do |format|
        format.html { render :preview, layout: false }
      end
    end

    # PATCH/PUT /mail_templates/1
    def update
      if @mail_template.update(mail_template_params)
        redirect_to mail_templates_path, notice: "Mail template successfully updated"
      else
        render :edit
        flash.now notice: "An error occurred updating the template."
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_mail_template
        @mail_template = MailTemplate.find(params[:id])
      end

      def preview_params
        params.permit(:content)
      end

      # Only allow a trusted parameter "white list" through.
      def mail_template_params
        params.require(:mail_template).permit(:name, :description, :subject, :content)
      end
  end
end

app/views/email_me/mail_templates/_form.html.erb
<%= simple_form_for @mail_template do |f| %>
  <%= f.input :name, input_html: { readonly: true} %>
  <%= f.input :description %>
  <%= f.input :subject %>
  <div class="row">
    <div class="col-md-8">
      <%= f.input :content %>
    </div>
    <% unless @replacement_fields.empty? %>
      <div class="col-md-4">
        <div class="form-group">
          <label class="control-label"><%= t 'email_me.form.replacement_field_label' %></label>
          <p><%= t 'email_me.form.replacement_field_instr' %></p>
          <dl>
            <% @replacement_fields.each do |field, desc| %>
              <dt><%= field %></dt>
              <dd><%= desc %></dd>
            <% end %>
          </dl>
        </div>
      </div>
    <% end %>
  </div>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn btn-link' %>
<% end %>

<%= javascript_tag do %>
  $(function(){
    $('#mail_template_content').markdownEditor({
      preview: true,
      fullscreen: false,
      imageUpload: false,
      height: '400px',
      onPreview: function (content, callback) {
        $.ajax({
          url: 'preview',
          type: 'POST',
          dataType: 'html',
          data: {content: content},
        })
        .done(function(result) {
          // Return the html:
          callback(result);
        });
      }
    });
  });
<% end %>

app/views/email_me/mail_templates/_index_body.html.erb
<h1><%= t 'email_me.index_body.header' %></h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t 'email_me.index_body.subject_header' %></th>
    <th scope="col"><%= t 'email_me.index_body.description_header' %></th>
    <td class="empty-header"></td>
  </tr>
  </thead>
  <tbody>
  <% @mail_templates.each do |mail_template| %>
    <tr>
      <td><%= mail_template.subject %></td>
      <td><%= mail_template.description %></td>
      <td><%= link_to 'Edit', edit_mail_template_path(mail_template), class: "btn btn-default btn-xs" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/email_me/mail_templates/edit.html.erb
<h1><%= t 'email_me.edit.header' %></h1>

<%= render "form" %>

app/views/email_me/mail_templates/index.html.erb
<%= render "index_body" %>

app/views/email_me/mail_templates/preview.html.erb
<%= @preview_html.html_safe %>